select  
dayid,
session_key,
playlistid,
publisher,           
show,             
asset_name,          
assetid,                   
platform,                
sum(playback) as playbacks,         
sum(video_played_in_minute) as play_minutes,
sum(num_follow) as num_follow,        
sum(num_unfollow) as num_unfollow,
sum(num_copyurlsharevideo) as num_copyurlsharevideo,
sum(num_emailsharevideo) as num_emailsharevideo,
sum(num_facebooksharevideo) as num_facebooksharevideo,
sum(num_twittersharevideo) as num_twittersharevideo,
sum(num_copyurlshareplaylist) as num_copyurlshareplaylist,
sum(num_emailshareplaylist) as num_emailshareplaylist,
sum(num_facebookshareplaylist) as num_facebookshareplaylist,
sum(num_twittershareplaylist) as num_twittershareplaylist
group by      
dayid,
session_key,
playlistid,
publisher,           
show,             
asset_name,          
assetid,                   
platform